---
dependency:
  name: galaxy
  enabled: true

driver:
  name: docker

platforms:
  - name: instance
    image: "fedora:${MOLECULE_DISTRO:-42}"
    pre_build_image: true
    command: "sleep infinity"

provisioner:
  name: ansible

verifier:
  name: ansible