---
dependency:
  name: galaxy
  enabled: false

driver:
  name: docker

platforms:
  - name: instance
    image: "fedora:${MOLECULE_DISTRO:-42}"
    pre_build_image: true
    privileged: true
    command: "/usr/sbin/init"
    tmpfs:
      - /run
      - /tmp

provisioner:
  name: ansible

verifier:
  name: ansible