---
driver:
  name: docker

platforms:
  - name: instance
    image: "quay.io/fedora/fedora:${MOLECULE_DISTRO:-39}"
    pre_build_image: true
    privileged: true
    command: "/usr/sbin/init"
    tmpfs:
      - /run
      - /tmp

provisioner:
  name: ansible

verifier:
  name: ansible