name: Molecule CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: 
          - "39"
          - "40"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Molecule Tests
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_working_dir: .
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}